import { signUp, validateRequest } from "@/actions/authActions";
import AuthForm from "@/components/AuthForm";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

export default async function page() {
  const { user } = await validateRequest();
  if (user) return redirect("/dashboard");
  return (
    <main className="flex items-center justify-center">
      <AuthForm type="signup" action={signUp} />
    </main>
  );
}
