import ExpenseOverviewCard from "@/components/ExpenseOverviewCard";
import type { Metadata } from "next";
import { Suspense } from "react";
import ExpOverviewCardLoading from "@/components/loading/ExpOverviewCardLoading";
import TransactionTable from "@/components/sections/TransactionTable";
import TransactionTableLoading from "@/components/loading/TransactionTableLoading";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function page() {
  return (
    <section id="section" className="scale-100">
      {/* expenses */}
      <div className="flex flex-wrap gap-4 p-4 max-w-screen-xl mx-auto">
        <Suspense fallback={<ExpOverviewCardLoading />}>
          <ExpenseOverviewCard title="Total Expenses" />
        </Suspense>
        <Suspense fallback={<ExpOverviewCardLoading />}>
          <ExpenseOverviewCard title="This month expenses" showThisMonth />
        </Suspense>
        <Suspense fallback={<ExpOverviewCardLoading />}>
          <ExpenseOverviewCard title="Average expenses per month" showAvg />
        </Suspense>
      </div>

      {/* table */}
      <div className="flex p-4 max-w-screen-xl mx-auto">
        <Suspense fallback={<TransactionTableLoading />}>
          <TransactionTable />
        </Suspense>
      </div>
    </section>
  );
}
