import ExpenseOverviewCard from "@/components/ExpenseOverviewCard";
import DataTable from "@/components/table/data-table";
import { columns } from "@/components/table/column-defination";
import { payments } from "@/lib/table/tempData";
import type { Metadata } from "next";
import { getCategory, getTransaction } from "@/lib/dbFunctions/db";
import { Suspense } from "react";
import ExpOverviewCardLoading from "@/components/loading/ExpOverviewCardLoading";
import { validateRequest } from "@/actions/authActions";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function page() {
  const { user } = await validateRequest();

  if (!user) return null;

  const categories = await getCategory(user.id);
  const result = await getTransaction(user.id);
  const transactions = result.map((item) => ({
    ...item.transaction,
    category: item.category.name,
  }));
  transactions.reverse();
  return (
    <>
      {/* expenses */}
      <div className="flex flex-wrap gap-4 p-4 max-w-screen-xl mx-auto">
        <Suspense fallback={<ExpOverviewCardLoading />}>
          <ExpenseOverviewCard title="Total Expenses" userId={user.id} />
        </Suspense>
        <Suspense fallback={<ExpOverviewCardLoading />}>
          <ExpenseOverviewCard
            title="This month expenses"
            currentDate
            userId={user.id}
          />
        </Suspense>
        <Suspense fallback={<ExpOverviewCardLoading />}>
          <ExpenseOverviewCard
            title="Average expenses per month"
            avg
            userId={user.id}
          />
        </Suspense>
      </div>

      {/* table */}
      <div className="flex p-4 max-w-screen-xl mx-auto">
        <DataTable
          categories={categories}
          userId={user.id}
          columns={columns}
          data={transactions}
        />
      </div>
    </>
  );
}
