import { login, validateRequest } from "@/actions/authActions";
import AuthForm from "@/components/AuthForm";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default async function page() {
  const { user } = await validateRequest();
  if (user) return redirect("/dashboard");
  return (
    <main className="flex items-center justify-center">
      <AuthForm type="login" action={login} />
    </main>
  );
}
